#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>

QT_BEGIN_NAMESPACE
namespace Ui {
class MainWindow;
}
QT_END_NAMESPACE

/**
 * @class MainWindow
 * @brief A simple Notepad-like text editor built using Qt.
 *
 * The MainWindow class provides the core functionality of the application,
 * including file operations (new, open, save, save as), text editing actions
 * (undo, redo, cut, copy, paste), and an About dialog.
 */
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    /**
     * @brief Constructor for MainWindow.
     * @param parent The parent widget (default is nullptr).
     *
     * Initializes the main window and sets up the user interface.
     */
    MainWindow(QWidget *parent = nullptr);

    /**
     * @brief Destructor for MainWindow.
     *
     * Cleans up allocated resources.
     */
    ~MainWindow();

private slots:
    /**
     * @brief Creates a new file by clearing the editor.
     */
    void on_actionNew_triggered();

    /**
     * @brief Saves the current text to the existing file.
     */
    void on_actionSave_triggered();

    /**
     * @brief Saves the current text to a new file chosen by the user.
     */
    void on_actionSaveAs_triggered();

    /**
     * @brief Undoes the last text editing action.
     */
    void on_actionUndo_triggered();

    /**
     * @brief Cuts the selected text.
     */
    void on_actionCut_triggered();

    /**
     * @brief Copies the selected text.
     */
    void on_actionCopy_triggered();

    /**
     * @brief Pastes text from the clipboard.
     */
    void on_actionPaste_triggered();

    /**
     * @brief Redoes the last undone action.
     */
    void on_actionRedo_triggered();

    /**
     * @brief Opens an existing text file and loads its contents.
     */
    void on_actionOpen_triggered();

    /**
     * @brief Displays information about the Notepad application.
     */
    void on_actionNotepad_triggered();

private:
    Ui::MainWindow *ui;   ///< Pointer to the UI elements generated by Qt Designer
    QString file_path;    ///< Stores the path of the currently opened file
};

#endif // MAINWINDOW_H
